#%RAML 1.0
title: QueryHeaders API
version: v1
baseUri: https://api.codingmatters.org/query-headers
mediaType: application/json

/root:
    displayName: RootResource
    get:
        responses:
            200:
                body:
                    type: AType

types:
  !include subdir/types-with-includes.raml