#%RAML 1.0
title: SimpleResources API
version: v1
baseUri: https://api.codingmatters.org/simple-resources
mediaType: application/json

types:
    SimplePropertyType:
        type: object
        properties:
            simpleString: string
            complexString:
                type: string
            intArraySimple:
                type: array
                items: integer
            intArrayShortcut: integer[]
