#%RAML 1.0
title: SimpleResources API
version: v1
baseUri: https://api.codingmatters.org/simple-resources
mediaType: application/json


types:
    NestedType:
        type: object
        properties:
            nes-ted:
                type: object
                properties:
                    string-prop: string
                    enum-prop:
                      enum: [A, B, C]
                    enum-array-prop:
                      type: array
                      items:
                        enum: [D, E, F]
