#%RAML 1.0
title: Test API
version: v1
baseUri: https://api.codingmatters.org/test
mediaType: application/json

/root:
    displayName: Root
    get:
    delete:
    /child1:
      displayName: Child1
      get:
      /subchild:
        displayName: Subchild
        get:
    /child2:
      displayName: Child2
      get: