#%RAML 1.0
title: Test API
version: v1
baseUri: https://api.codingmatters.org/test
mediaType: application/json

/:
  displayName: Root
  get:
  /child:
    displayName: Child
    get:
  /{param}:
    displayName: ChildWithUriParam
    uriParameters:
      param: string
    get: