#%RAML 1.0
title: Test API
version: v1
baseUri: https://api.codingmatters.org/test
mediaType: application/json

/payload:
  displayName: Payload
  post:
    body: Req
    responses:
      200:
        body: Resp

/already:
   displayName: already
   post:
      body: AlreadyDefinedType
      responses:
         200:
            body: AlreadyDefinedType

types:
   Resp:
      type: object
      properties:
         prop: string
   Req:
      type: object
      properties:
         prop: string

   AlreadyDefinedType:
      (already-defined): org.codingmatters.AnAlreadyDefinedValueObject
      type: object


annotationTypes:
   value-object-hint:
      type: string[]
   conforms-to:
      type: string[]
   already-defined:
      type: string