#%RAML 1.0
title: Test API
version: v1
baseUri: https://api.codingmatters.org/test
mediaType: application/json

/payload:
  displayName: Payload
  post:
    body: Req

/query-params:
  displayName: QueryParams
  get:
    queryParameters:
      prop: string

types:
  Req:
    type: object
    properties:
      prop: string