#%RAML 1.0
title: Test API
version: v1
baseUri: https://api.codingmatters.org/test
mediaType: application/json

/payload:
  displayName: Payload
  post:
    body: Req
    responses:
      200:
        body: Resp

/already:
   displayName: already
   post:
      body: AlreadyDefinedType
      responses:
         200:
            body: AlreadyDefinedType

/alreadyArray:
   displayName: alreadyArray
   post:
      body: AlreadyDefinedType
      responses:
         200:
            body:
               type: array
               items: AlreadyDefinedType

/alreadyArrayLiteral:
   displayName: alreadyArrayLiteral
   post:
      body: AlreadyDefinedType
      responses:
         200:
            body: AlreadyDefinedType[]

types:
   Resp:
      type: object
      properties:
         prop: string
   Req:
      type: object
      properties:
         prop: string

   AlreadyDefinedType:
      (already-defined): org.codingmatters.AnAlreadyDefinedValueObject
      type: object


annotationTypes:
   value-object-hint:
      type: string[]
   conforms-to:
      type: string[]
   already-defined:
      type: string

traits:
   collectionPaging:
      usage: aplied to a collection GET
      description: pageable collection of <<elementType>>. Paging is handled with the range header (according to [RFC 7233](https://tools.ietf.org/html/rfc7233)).
      headers:
         range:
            type: string
            required: false
      responses:
         200:
             description: complete list of <<elementType>> or last elements of the list of <<elementType>>
             headers:
                 Content-Range: string
                 Accept-Range: string
             body: <<elementType>>[]