#%RAML 1.0
title: Test API
version: v1
baseUri: https://api.codingmatters.org/test
mediaType: application/json

/headers:
  displayName: Headers
  get:
    responses:
      200:
        headers:
          stringParam:
            type: string
          arrayParam:
            type: array
            items: string
          intParam:
            type: integer
          intArrayParam:
            type: array
            items: integer
          realParam:
            type: number
          realArrayParam:
            type: array
            items: number
          dateParam:
            type: date-only
          dateArrayParam:
            type: array
            items: date-only
          datetimeParam:
            type: datetime-only
          datetimeArrayParam:
            type: array
            items: datetime-only
          timeParam:
            type: time-only
          timeArrayParam:
            type: array
            items: time-only
          boolParam:
            type: boolean
          boolArrayParam:
            type: array
            items: boolean
/payload:
  displayName: Payload
  get:
    responses:
      200:
        body: Resp

/payload-list:
  displayName: PayloadList
  get:
    responses:
      200:
        body: Resp[]

/status:
  displayName: Status
  get:
    responses:
      200:
      201:
      202:

/arbitrary-object:
  displayName: ArbitraryObject
  get:
    responses:
      200:
        body: object

/arbitrary-object-array:
  displayName: ArbitraryObjectArray
  get:
    responses:
      200:
        body:
          type: array
          items: object

types:
  Resp:
    type: object
    properties:
      prop: string