#%RAML 1.0
title: Test API
version: v1
baseUri: https://api.codingmatters.org/test
mediaType: application/json

/payload:
  displayName: Payload
  post:
    body: Req

/query-params:
  displayName: QueryParams
  get:
    queryParameters:
      stringParam:
          type: string
      stringArrayParam:
          type: array
          items: string

/uri-param/{param}:
    displayName: UriParams
    uriParameters:
         param:
           type: string
    get:

types:
  Req:
    type: object
    properties:
      prop: string