#%RAML 1.0
title: SimpleResources API
version: v1
baseUri: https://api.codingmatters.org/simple-resources
mediaType: application/json

annotationTypes:
   already-defined:
      type: string



#/toto:
#  displayName: Toto
#  get:
#    responses:
#      200:

types:
    AlreadyDefinedType:
        (already-defined): org.codingmatters.AnExternalValueObject
        type: object

    IncludeADT:
      type: object
      properties:
        adt:
          type: AlreadyDefinedType
        adtShort: AlreadyDefinedType
        adtShortList: AlreadyDefinedType[]
        adtList:
          type: array
          items: AlreadyDefinedType

    TypeWithAlreadyDefinedProperty:
      type: object
      properties:
        prop:
          (already-defined): io.flexio.services.resources.api.types.Schema
          type: object
        propList:
          type: array
          items:
            type: object
            (already-defined): io.flexio.services.resources.api.types.Schema
