#%RAML 1.0
title: Test API
version: v1
baseUri: https://api.codingmatters.org/test
mediaType: application/json

/root:
    displayName: Root
    get:
    post:
    /sub:
        displayName: Sub
        get: