#%RAML 1.0
title: QueryHeaders API
version: v1
baseUri: https://api.codingmatters.org/query-headers
mediaType: application/json

annotationTypes:
   object-impl:
      enum: [ Val, ObjectValue ]

/root:
    displayName: RootResource
    get:
        body:
            type: AType

/file:
    displayName: FilePayload
    post:
        body:
            type: file

/object:
    displayName: ArbitraryObject
    post:
        body:
            type: object

/object-impl-val:
    displayName: ArbitraryObjectImplVal
    post:
        body:
            (object-impl): Val
            type: object

/object-impl-object-value:
    displayName: ArbitraryObjectImplObjectValue
    post:
        body:
            (object-impl): ObjectValue
            type: object


/string:
  displayName: StringPayload
  post:
    body:
      text/plain:
        type: string

types:
    AType:
        type: object