#%RAML 1.0
title: QueryHeaders API
version: v1
baseUri: https://api.codingmatters.org/query-headers
mediaType: application/json

/root:
    displayName: RootResource
    get:
        body:
            type: AType

/file:
    displayName: FilePayload
    post:
        body:
            type: file

/object:
    displayName: ArbitraryObject
    post:
        body:
            type: object

types:
    AType:
        type: object