#%RAML 1.0
title: QueryHeaders API
version: v1
baseUri: https://api.codingmatters.org/query-headers
mediaType: application/json

annotationTypes:
   object-impl:
      enum: [ Val, ObjectValue ]

/root:
    displayName: RootResource
    get:
        responses:
            200:
                body:
                    type: AType

/stringPayload:
   displayName: StringPayload
   get:
      responses:
         200:
            body:
               type: string

/filePayload:
   displayName: FilePayload
   get:
      responses:
         200:
            body: file

/objctPayload:
   displayName: ObjectPayload
   get:
      responses:
         200:
            body: object
         201:
            body:
              (object-impl): Val
              type: object
         202:
            body:
              (object-impl): ObjectValue
              type: object

types:
    AType:
        type: object