#%RAML 1.0
title: SimpleResources API
version: v1
baseUri: https://api.codingmatters.org/simple-resources
mediaType: application/json


annotationTypes:
   value-object-hint:
      type: string[]
   conforms-to:
      type: string[]
   already-defined:
      type: string

/root:
    displayName: RootResource
    get:
    post:
    put:
    delete:
    head:
    patch:
    options:
    /middle:
        displayName: MiddleResource
        get:
        /leaf-1:
            displayName: FirstResource
            get:
        /leaf-2:
            displayName: SecondResource
            get:



/obj:
    displayName: Obj
    get:
        body: object
        responses:
            200:
                body: object
/obj-array:
    displayName: ObjArray
    get:
        body:
            type: array
            items: object
        responses:
            200:
                body:
                    type: array
                    items: object
/obj-array-inline:
    displayName: ObjArrayInline
    get:
        body: object[]
        responses:
            200:
                body: object[]

/simple-type:
    displayName: SimpleType
    get:
        body: SimpleType
        responses:
            200:
               body: SimpleType
/simple-type-array:
    displayName: SimpleTypeArray
    get:
        body:
            type: array
            items: SimpleType
        responses:
            200:
               body:
                   type: array
                   items: SimpleType
/simple-type-array-inline:
    displayName: SimpleTypeArrayInline
    get:
        body: SimpleType[]
        responses:
            200:
               body: SimpleType[]

/already-defined-request-and-response-body:
    displayName: AlreadyDefinedRequestAndResponseBody
    get:
        body: AlreadyDefinedType
        responses:
            200:
               body: AlreadyDefinedType

/already-defined-array-request-and-response-body:
    displayName: AlreadyDefinedArrayRequestAndResponseBody
    get:
        body:
            type: array
            items: AlreadyDefinedType
        responses:
            200:
               body:
                  type: array
                  items: AlreadyDefinedType
/already-defined-inline-array-request-and-response-body:
    displayName: AlreadyDefinedInlineArrayRequestAndResponseBody
    get:
        body: AlreadyDefinedType[]
        responses:
            200:
               body: AlreadyDefinedType[]

types:
    SimpleType:
        type: object
        properties:
            prop: string

    AlreadyDefinedType:
        (already-defined): org.codingmatters.AnAlreadyDefinedValueObject
        type: object