#%RAML 1.0
title: SimpleResources API
version: v1
baseUri: https://api.codingmatters.org/simple-resources
mediaType: application/json


annotationTypes:
   value-object-hint:
      type: string[]
   conforms-to:
      type: string[]
   builder-conforms-to:
      type: string[]
   already-defined:
      type: string
   object-impl:
      enum: [ Val, ObjectValue ]

types:
    SimplePropertyType:
        type: object
        properties:
            stringProp:
                type: string
            stringArrayProp:
                type: array
                items: string
            intProp: integer
            intArrayProp:
                type: array
                items: integer
            enumProp:
              enum: [A, B, C]
            enumArrayProp:
              type: array
              items:
                enum: [A, B, C]


    NestedType:
        type: object
        properties:
            nested:
                type: object
                properties:
                    stringProp: string
                    nested-prop:
                        type: object
                        properties:
                            stringProp: string
                            enumProp:
                              enum: [A, B, C]
                            enumArrayProp:
                              type: array
                              items:
                                enum: [A, B, C]
                            deeply-nested:
                              type: object
                              properties:
                                d-n-s: string
                                enven-more-deeply-nester:
                                  type: object
                                  properties:
                                    e-m-d-n-s: string
            nestedArray:
                type: array
                items:
                    type: object
                    properties:
                        stringProp: string

    ReferencesType:
        type: object
        properties:
            reference: SimplePropertyType
            typeReference:
                type: SimplePropertyType
            referenceArray: SimplePropertyType[]
            typeReferenceArray:
                type: array
                items: SimplePropertyType


    RawPropertyNameType:
        type: object
        properties:
            Raw Property Name: string

    TypeWithHint:
        type: object
        properties:
            annotated:
                type: string
                (value-object-hint):
                    - mongo:object-id
                    - mongo:field(_id)

    TypeWithProtocol:
        (conforms-to): [java.io.Serializable]
        (builder-conforms-to): [java.io.Serializable]
        type: object

    TypeWithObjectProperty:
        type: object
        properties:
            obj: object
            objVal:
              type: object
              (object-impl): Val

            objs:
               type: array
               items: object
            objVals:
               type: array
               (object-impl): Val
               items:
                type: object

    AlreadyDefinedType:
        (already-defined): org.codingmatters.AnExternalValueObject
        type: object

    TypeWithAlreadyDefinedProperty:
        type: object
        properties:
            prop:
                (already-defined): org.codingmatters.AnAlreadyDefinedValueObject
                type: object
            props:
                type: array
                items:
                  type: object
                  (already-defined): org.codingmatters.AnAlreadyDefinedValueObject
            deeper:
                type: object
                properties:
                   prop:
                      (already-defined): org.codingmatters.AnAlreadyDefinedValueObject
                      type: object

