#%RAML 1.0
title: SimpleResources API
version: v1
baseUri: https://api.codingmatters.org/simple-resources
mediaType: application/json

annotationTypes:
   already-defined:
      type: string

types:
    AlreadyDefinedType:
        (already-defined): org.codingmatters.AnExternalValueObject
        type: object

    IncludeADT:
      type: object
      properties:
        adt:
          type: AlreadyDefinedType
        adtShort: AlreadyDefinedType
        adtShortList: AlreadyDefinedType[]
        adtList:
          type: array
          items: AlreadyDefinedType