---

NettyHttpConfig:
  host: string
  port: int
  bossCount: int
  workerCount: int
  maxInitialLineLength: int
  maxHeaderSize: int
  maxChunkSize: int
  initialBufferSize: int
  maxPayloadSize: int

  validateHeaders: bool
  allowDuplicateContentLengths: bool
  allowPartialChunks: bool
