#%RAML 1.0
title: SimpleResources API
version: v1
baseUri: https://api.codingmatters.org/simple-resources
mediaType: application/json

types:
  LittleObject:
    type: object
    properties:
      name: string

  RootObj:
    type: object
    properties:
      titi: string
      grosminet: integer
      day:
        enum: [ LUNDI, MARDI ]
      date: datetime
      little: LittleObject
      list: LittleObject[]


/root:
    displayName: Root
    get:
    post:
    /sub:
        displayName: Sub
        get:
          responses:
            200:
              body: LittleObject
            201:
              body: RootObj
            302:
              body: object
        post:
          body: RootObj
    /query/me:
        displayName: Query me
        get:
          queryParameters:
            toto: string
            titi: string
    /uri/{param}/here:
        displayName: Uri Param
        uriParameters:
          param: string
        patch:
    /head/shot:
      displayName: Headed query
      put:
        headers:
          x-name: string



