#%RAML 1.0
title: SimpleResources API
version: v1
baseUri: https://api.codingmatters.org/simple-resources
mediaType: application/json

types:
  LittleObject:
    type: object
    properties:
      name: string

  RootObj:
    type: object
    properties:
      titi: string
      grosminet: integer
      day:
        enum: [ LUNDI, MARDI ]
      date: datetime
      little: LittleObject
      list: LittleObject[]


/root:
    displayName: Root
    patch:
      body: RootObj
    put:
      body: RootObj[]
    delete:
      body: object
    get:
    post:
      body: object[]
    /sub:
        displayName: Sub
        get:
          body: file
          responses:
            200:
              body: LittleObject
            201:
              body: RootObj
            302:
              body: object
              headers:
                X-entity-id: string
        post:
          body:
            type: array
            items: object
          responses:
            200:
        patch:
          body:
            type: array
            items: RootObj
    /query/me:
        displayName: Query me
        get:
          queryParameters:
            toto: string
            titi: string
    /uri/{param}/here:
        displayName: Uri Param
        uriParameters:
          param: string
        patch:
    /head/shot:
      displayName: Headed query
      put:
        headers:
          x-name: string



/second:
  displayName: Second