#%RAML 1.0
title: SimpleResources API
version: v1
baseUri: https://api.codingmatters.org/simple-resources
mediaType: application/json

/root:
    displayName: Root
    get:
    post:
    /sub:
        displayName: Sub
        get: